exclude: |
  (?x)^(
      docs/source/conf.py|
      tests/[\w]*.py|
      tools/[\w]*.py|
      reports/[\w]*|
      examples/[\w]*.py|
      tasks.py|
      post_installation.py
      templater.py
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
        args: [--maxkb=600]
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.8
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pycqa/isort
    rev: 8.0.0
    hooks:
      - id: isort
        args: ["--filter-files"]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.1.0
    hooks:
      - id: black
        alias: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          #          - flake8-bugbear
          #          - flake8-comprehensions
          #          - flake8-eradicate
          - flake8-simplify
        args: ["--ignore=C901,E800,F842,F841,W503"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py39]


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        alias: mypy
        args:
          [
            --ignore-missing-imports,
            --disallow-untyped-defs,
            --no-warn-unused-ignores,
            --install-types,
            --html-report,
            "reports/mypy",
            --cache-dir,
            "cache/.mypy_cache",
          ]
        additional_dependencies:
          - types-dataclasses >= 0.1.3
          - lxml
          - types-click
          - types-beautifulsoup4
          - types-html5lib
          - types-PyYAML
          - types-requests
          - types-urllib3
          - types-python-dateutil

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.3
    hooks:
      - id: bandit
        args:
          - -s
          - B101,B301,B324,B403,B404,B602,B603,B607

  - repo: meta
    hooks:
      - id: check-useless-excludes
